version:                "1"
services:
  risk_scale:
    image: jupyter/datascience-notebook:julia-1.9.1
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/work/data
      - ./data_raw:/home/jovyan/work/data_raw
      - ./results:/home/jovyan/work/results
      - ./risk:/home/jovyan/work/risk
    ports:
      - 8007:8888
    environment:
      - JUPYTER_TOKEN=hi
    container_name: risk_scale
